name: Run Python Script Automatically

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 8 * * *"    # 8:00 AM
  #   - cron: "00 18 * * *"  # 6:00 PM
  #   - cron: "0 0 * * *"    # 00:00 AM (midnight)



jobs:
  run-script:
    runs-on: ubuntu-latest  # Use a Linux environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Specify your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pushbullet.py  # Install the Pushbullet library

      - name: Run Python Script
        env:
          BREVO_KEY: ${{ secrets.BREVO_KEY }}  # Pass the secret to the script
        run: python script.py
